id: IMP-102
story: story-003
title: IMP-102
status: done
created: 2025-09-20
updated: 2025-09-20
type: chore
acceptance:
  - Gracefully handles empty layers (returns minimal array or placeholder)
  - Flattens layer content into ordered string segments preserving priority
  - Excludes disabled layers (future-proof: skip if `enabled === false` when field exists)
  - Exported utility available via `@taskly/ai`
  - Unit test scaffold placeholder (implemented as `packages/ai/src/instructionAdapter.spec.ts`)
