id: TOOL-003
story: story-004
title: TOOL-003
status: done
created: 2025-09-19
updated: 2025-09-19
type: feature
owner: system
related: [[story:10-engineering-automation]]
acceptance:
  - Husky installed with `prepare` script
  - Pre-commit runs `pnpm tasks:validate`
  - Commit blocked if validator fails
  - Commit blocked if staged paths match `apps/*/.next/`
  - Document workflow in CONTRIBUTING
