id: TOOL-006
story: story-004
title: TOOL-006
status: done
created: 2025-09-19
updated: 2025-09-19
type: feature
owner: system
related: [[story:10-engineering-automation]]
acceptance:
  - Reports unresolved story references
  - Reports unresolved task references
  - Warns (not fails) on missing reciprocal links
  - Exit code non-zero only on unresolved references
