name: Tasks Governance
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Validate tasks
        run: pnpm tasks:validate
      - name: Generate spec index (expected clean)
        run: pnpm spec:index
      - name: Generate manifest (expected clean)
        run: pnpm tasks:manifest
      - name: Detect dirty repo (spec index / manifest must be committed)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Repository dirty after generation steps. Commit updated tasks.yaml / SPEC-INDEX.md.";
            git status --porcelain;
            exit 1;
          fi
